# One of 'error', 'warn', 'info', 'verbose', debug', 'silly'
loglevel: 'debug'
ESlogging:
    enabled: false
    label: SHELLY2INFLUXDB
    loglevel: info
    options:
        indexPrefix: logs
        clientOpts:
            node: http://es.elastic.home

# Configuration passed to the node-influx library
influx:
  database: 'shellypm'
  host: 'localhost'
  port: 8086

databases:
  - name: 'shellypm'
    retentionPolicies:
    - name: 14d
      duration: 14d


# Polling interval (seconds)
interval: 5

energy:
  database: 'shellypm'
  measurement: shellypm_energy


# Shelly power measurement units
shellypm:
  - url: http://192.168.1.60/rpc/Shelly.GetStatus
    energy:
        label: airco-bureau
        value: pm1:0.aenergy.total
        force_increasing: true
    measurements:
      - measurement: shellypm_other
        tags:
          label: airco-bureau
        fields:
          value: $.pm1:0.aenergy.total

  - url: http://192.168.1.61/rpc/Shelly.GetStatus
    energy:
        label: pc
        value: pm1:0.aenergy.total
    measurements:
      - measurement: shellypm_other
        tags:
          label: pc
        fields:
          value: $.pm1:0.aenergy.total
