# One of 'error', 'warn', 'info', 'verbose', debug', 'silly'
loglevel: 'verbose'
ESlogging:
    enabled: false
    label: SHELLY2INFLUXDB
    loglevel: info
    options:
        indexPrefix: logs
        clientOpts:
            node: http://es.elastic.home

# Configuration passed to the node-influx library
influx:
  database: 'shellypm'
  host: 'influxdb.k3s.home'
  port: 80

# Polling interval (seconds)
interval: 900

# Shelly power measurement units
shellypm:
  - url: http://192.168.1.60/rpc/Shelly.GetStatus
    measurements:
      - measurement: shellypm_energy
        tags:
          label: shellypmminig3-airco-bureau
        fields:
          value: $.pm1:0.aenergy.total

  - url: http://192.168.1.61/rpc/Shelly.GetStatus
    measurements:
      - measurement: shellypm_energy
        tags:
          label: shellypmminig3-airco-pc
        fields:
          value: $.pm1:0.aenergy.total
